# Generated by Django 4.1.7 on 2023-03-27 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('EMPLOYEE_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONE_NUMBER', models.CharField(max_length=20)),
                ('HIRE_DATE', models.DateField()),
                ('JOB_ID', models.CharField(max_length=10)),
                ('SALARY', models.DecimalField(decimal_places=2, max_digits=8)),
                ('COMMISSION_PCT', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('DEPARTMENT_ID', models.IntegerField()),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='workers.workers')),
            ],
        ),
    ]
